INSERT INTO TEAM (ID, NAME) VALUES (1, 'Team Alpha');
INSERT INTO TEAM (ID, NAME) VALUES (2, 'Team Beta');

INSERT INTO HERO (ID, NAME, ROLE, healthPoints, ABILITIES, TEAM_ID) VALUES (1, 'Hero1', 'Warrior', 1000, 'Slash, Shield Bash', 1);
INSERT INTO HERO (ID, NAME, ROLE, healthPoints, ABILITIES, TEAM_ID) VALUES (2, 'Hero2', 'Mage', 800, 'Fireball, Teleport', 2);

INSERT INTO PLAYER (ID, NAME, EMAIL, LEVEL, EXPERIENCE_POINTS, TEAM_ID) VALUES (1, 'Player1', 'player1@example.com', 10, 1500, 1);
INSERT INTO PLAYER (ID, NAME, EMAIL, LEVEL, EXPERIENCE_POINTS, TEAM_ID) VALUES (2, 'Player2', 'player2@example.com', 12, 1800, 2);

INSERT INTO MATCH (ID, DATE, STATUS, DURATION, TEAM1_ID, TEAM2_ID, WINNER_ID) VALUES (1, CURRENT_TIMESTAMP, 'Completed', 35, 1, 2, 1);
